# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :ad_hoc do
    unlock_keychain(
      path: "/Users/blade/Library/Keychains/login.keychain-db",
      password: "2018"
    )
    build_app(
      scheme: "i点集",
      export_method: "ad-hoc",
      codesigning_identity: "iPhone Distribution: Fortune Network"
    )
  end
end
