# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"

  lane :development do
    build_app(
      scheme: "dgApp",
      export_method: "development",
      output_directory: "build"
    )
  end

  lane :ad_hoc do
    build_app(
      silent: true,
      clean: false,
      scheme: "dgApp",
      export_method: "ad-hoc",
      output_directory: "build"
    )
  end

  lane :sync_devices do
    register_devices(devices_file: "./fastlane/devices.txt")
    match(type: "adhoc", force_for_new_devices: true)
  end
end
